### PR TITLE
Use timeouts in all HTTP requests.

### PR DESCRIPTION
**Pull request by jtwalters**

### CODE REVIEW

**Comment by iamEAP** [comment]
Seems important enough to add a test. Potentially, [here](https://github.com/tableau-mkt/elomentary/blob/master/test/src/HttpClient/HttpClientTest.php#L327) to cover all request types? Maybe a better place for it. @jtwalters?

**Comment by jtwalters** [comment]
That seems reasonable. What is the strategy for testing timeouts in PHP? I'm not too familiar with PHPUnit.

**Comment by iamEAP** [comment]
I think the main thing to test is just that `ClientInterface::createReqest()` ($this->client) gets called with at least a `timeout` and `connection_timeout` set in the arguments as configured. No need to test actual timeouts.

**Comment by iamEAP** [comment]
_6 months later..._  Thanks for diving into this @jtwalters.  I went ahead and added a test to cover this. Merging.

**Pull request merged**
